### ISSUE TITLE
css无效

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#173]
demo.css

``` css
.ycm-bar {
    position: fixed;
    z-index: 10;
    right: 0;
    left: 0;
    height: 88px;
    padding-right: 20px;
    padding-left: 20px;
    border-bottom: 0;
    background-color: #f7f7f7;
    box-shadow: 0 0 2px rgba(0,0,0,.85);
    box-shadow: 0 0 2px rgba(0,0,0,.85);
    backface-visibility: hidden;
}

.ycm-title{
    text-align: center;
    margin: 0;
    text-overflow: ellipsis;
    color: #000;
    font-size: 32px;
    line-height: 88px;
}
```

index.we

``` html
<template>
<div >
    <header class="ycm-bar ycm-bar-nav">
      <text class="ycm-title">YCM</text>
    </header>
</div>
</template>
```

1.发现ycm-title 中的line-height没有起作用

将CSS改为如下

``` css
.ycm-bar {
    position: fixed;
    z-index: 10;
    right: 0;
    left: 0;
    height: 88px;
    padding-right: 20px;
    padding-left: 20px;
    border-bottom: 0;
    background-color: #f7f7f7;
    box-shadow: 0 0 2px rgba(0,0,0,.85);
    box-shadow: 0 0 2px rgba(0,0,0,.85);
    backface-visibility: hidden;
}
.ycm-bar .ycm-title{
    text-align: center;
    margin: 0;
    text-overflow: ellipsis;
    color: #000;
    font-size: 32px;
    line-height: 88px;
}
```

2.发现整个ycm-title样式都不起作用，也就是说，weex不支持CSS的父级于子级的关系和继承吗？
