### ISSUE TITLE
css样式不兼容

### ISSUE THREAD

**Issue by liwenyou** [alibaba/weex#1767]
1、先上图
![simulator screen shot 2016 11 29 16 22 09](https://cloud.githubusercontent.com/assets/8529588/20702051/0846b08e-b651-11e6-9dcb-946f1f6fe520.png)
![2016-11-29 16 24 12](https://cloud.githubusercontent.com/assets/8529588/20702052/0a66fc20-b651-11e6-9aed-f1d26e55ca3b.png)
![80a39d2edcaf1616366b4c37798a66c5](https://cloud.githubusercontent.com/assets/8529588/20702054/0c32abb2-b651-11e6-9af4-5842dd5cb053.png)
2.环境：
版本：
iOS x , weex 0.8.0正常；iOS x，weex 0.7 transform: rotate(45deg);失败；
浏览器正常；
安卓只测试了0.8.2，失败
3.代码：
1)style 片段
```css
.div-flag {
    transform: rotate(45deg);
    -ms-transform:rotate(45deg); 	/* IE 9 */
    -moz-transform:rotate(45deg); 	/* Firefox */
    -webkit-transform:rotate(45deg); /* Safari 和 Chrome */
    -o-transform:rotate(45deg); 	/* Opera */
    position: absolute;
    top: -37px;
    right: -37px;
    width: 140px;
    height: 30px;
    background-color: red;
    justify-content: center;
    align-items: center;
    /*overflow-clip: ;*/
    margin-top: 53px;
    margin-bottom: 53px;
}
```
2)html 片段
<img width="150" alt="2016-11-29 16 35 49" src="https://cloud.githubusercontent.com/assets/8529588/20702325/52688b14-b652-11e6-8ea1-1dff31225d79.png">

```html
<div class="div-flag"  if="{{bind_data.rightcont != ''}}">
            <text class="text-flag">测试是</text>
</div>
```
