### ISSUE TITLE
background-color的一些困惑

### ISSUE THREAD

**Issue by Demon-liao** [alibaba/weex#218]
**tpl**

``` html
<div  onclick="{{itemClick(INDEX)}}" class="OilItem OilItem_{{IsDefault}}" index="{{id}}" repeat="{{OilItems}}" >
    <text class="f28 OilItem-tx OilItem-tx-{{IsDefault}}">{{OilName}}</text>
</div>
```

**css**

``` css
.OilItem{
    flex:1;
    width: 135px;
    height: 76px;
    border-width:  1px;
    border-color: #ff7519;
    border-radius: 10px;
    text-align: center;
    position: relative;
    font-size: 28px;
    margin-left: 10px;
 }
 .OilItem_true{
  background-color: #ff7519
 }
 .OilItem-tx{
    text-align: center;
    padding-top: 18px;
     color: #ff7519;
 }
 .OilItem-tx-true{
    color: #fff
 }
```

**Data数据**

``` javascript
[
  {
    "id": 1,
    "OilName": "100元",
    "OilCode": "OilItem_10001",
    "Discount": "9.95折",
    "IsDefault": "false",
    "ItemPrice": 99.5
  },
  {
    "id": 2,
    "OilName": "200元",
    "OilCode": "OilItem_88888",
    "Discount": "9.95折",
    "IsDefault": "false",
    "ItemPrice": 199
  },
  {
    "id": 3,
    "OilName": "500元",
    "OilCode": "OilItem_10003",
    "Discount": "9.95折",
    "IsDefault": "true",
    "ItemPrice": 497.5
  },
  {
    "id": 4,
    "OilName": "1000元",
    "OilCode": "OilItem_10004",
    "Discount": "9.95折",
    "IsDefault": "false",
    "ItemPrice": 995
  }
]
```

**问题描述**
1.默认状态用repeat 循环的时候，遇到IsDefault值为true的时候，按钮显示橘色，字体为白色。这个效果已经实现。
2.当我改变data里面数据的时候，比如，我把id为2的数据中的IsDefault改为true，其他的数据的IsDefault都改成false，第二个按钮状态变成选中状态，但是之前选中状态的按钮，字体颜色改了，背景颜色确还是之前的样式，没改变。
3.根据我的猜测，在修改下默认状态的CSS，增加了  background-color: transparent; 然后效果就达到我想要的标准了。
4.以我的猜想，weex里面的所有的样式绑定都是一次性的，如果想要换掉之前的样式，就必须也要定义一次。
5.能否在相关文档中添加一些解释和说明，我相信大家写CSS的习惯，要实现两个class之间的效果切换，肯定不清楚需要两个状态都要定义覆盖，以为拿掉一个class，自然会显示出默认的样式出来。
