### ISSUE TITLE
[ios] vue模式下，if 切换 cell 导致组件的 style 没有正确更新

### ISSUE THREAD

**Issue by Neeeo** [alibaba/weex#2442]
如下 demo，点击切换后 cell 里的 div 样式变成两个的合集，而不是替换。
两个 cell 的样式区别在圆角上。
```vue
<template>
  <list class="wrapper">
      <cell v-if="show" @click="update">
        <div class="bottom">
        </div>
      </cell>
      <cell v-if="!show" @click="update">
        <div class="top">
        </div>
      </cell>
  </list>
</template>

<style>
  .bottom {
    margin-top: 120px;
    background-color: green; 
    border-top-left-radius: 20px; 
    border-top-right-radius: 20px;
    height: 300px;
    overflow: hidden;

  }
  .top {
    margin-top: 120px;
    background-color: red; 
    border-radius: 20px;
    height: 300px;
    overflow: hidden;
  }
  .wrapper { 
    top: 0; 
    left: 0; 
    right: 0; 
    bottom: 0; 
    width: 750;
    background-color: gray;
  }
</style>

<script>
  export default {
    data: {
      show: true,
    },
    methods: {
      update: function (e) {
        this.show = !this.show;
    }
  }
}
</script>
```

从 `inspector` 能看到，两个的样式被合并了：
```css
{
    height: 300;
    borderTopRightRadius: 20;
    borderRadius: 20;
    marginTop: 120;
    overflow: hidden;
    backgroundColor: #FF0000;
    borderTopLeftRadius: 20;
}
```
