### ISSUE TITLE
absolute div which has a -80 top value is not rendering on android

### ISSUE THREAD

**Issue by MrRaindrop** [alibaba/weex#796]
if a div has a negative top value, like:

``` css
.tag {
  position: absolute;
  top: -80px
}
```

Then it won't appear on the page. That's because:
1. in android, default value of `overflow` is `hidden`
2. in android, it's not supported to specify the parent with `overflow:visible`

But on web (and for w3c standard), it's `overflow:visible` by default. As I know, iOS is also `vislbie`.
