### ISSUE TITLE
[Proposal] Support pseudo-class like :hover

### ISSUE THREAD

**Issue by Jinjiang** [alibaba/weex#942]
**Summary:**

We can treat pseudo-class as normal class with every style prop name a pseudo-class prefix. For example: `.class-a:focus { color: red; }` equals to `.class-a { -focus-color: red; }`

**Description:**

_CSS syntax Design:_

``` css
.class-a { color: blue; }
.class-a:focus { color: red; } /* pseudo-class */
.class-a { -focus-color: red; } /* same effect */
```

_JS Bundle Format:_

``` javascript
{
  "class-a": {
    "color": "blue",
    "-focus-color": "red"
  }
}
```

_Renderer Implementation:_

Support `color` style and `-focus-color` when user tap on it. The interaction will not fire any JS task so it's faster than event.
